import React, { useState, useRef, useEffect } from "react";
import Navbar from "./navbar";
import Header from "./Header";
import ShoutCups from "./ShoutCups";
import Chegerma from "./Chegerma";
import ViewModalDiv from "./ViewModalDiv";
import Arzon from "./Arzon";
import Cardes from "./Cardes";

const Home = () => {
  const [data, setDate] = useState([
    {
      id: 1,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: true,
      skidka: false,
      rating: 1,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 2,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: true,
      skidka: false,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 3,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: true,
      skidka: false,
      rating: 2,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 4,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: true,
      skidka: false,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 5,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 6,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 7,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 8,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 9,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 10,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 11,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 12,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 13,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 14,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 15,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 16,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 17,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 18,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 19,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 20,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 21,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 1,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 22,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 23,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 2,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 24,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 25,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 26,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 27,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 28,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 29,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 30,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 31,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 32,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 33,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 34,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 35,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 36,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 37,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 38,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 39,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: true,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 40,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: false,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 41,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: false,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 42,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: false,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
    {
      id: 43,
      Images: ["1.png", "2.png", "3.png", "4.png"],
      shortName: "O'yin uchun monitor Redragon...",
      fullName: "O'yin uchun monitor Redragon Mirror 27, 165Hz, FHD, IPS, 1ms",
      oldPrice: "3 460 00 so'm",
      newPrice: "2 700 000 so'm",
      chegiram: false,
      skidka: false,
      rating: 3,
      zakazlar: 1,
      sotuvchi: "Shoyka Loyka",
    },
  ]);
  const [modalData, setModalData] = useState([]);
  const [openModal, setOpenModal] = useState(false);
  const [currentImageIndex, setCurrentImageIndex] = useState(0);

  const onViewCard = (obj) => {
    setModalData([]);
    setOpenModal(true);
    setModalData([obj]);
    console.log(modalData);
  };

  return (
    <div className="container">
      <Navbar />
      {openModal === false ? (
        <div>
          <Header />
          <ShoutCups />
          <div className="oonli">
            <Chegerma
              data={data}
              onViewCard={(obj, index) => onViewCard(obj, index)}
            />
            <Arzon data={data} onViewCard={(obj) => onViewCard(obj)} />
          </div>
          <Cardes data={data} onViewCard={(obj) => onViewCard(obj)} />
        </div>
      ) : (
        <>
          <ViewModalDiv
            setModalData={setModalData}
            modalData={modalData}
            currentImageIndex={currentImageIndex}
            setCurrentImageIndex={setCurrentImageIndex}
          />
        </>
      )}
    </div>
  );
};

export default Home;
